server:
  port: 8080

spring:
  redis:
    port: 6379
    password: 123456
    host: 192.168.174.128
    jedis:
      pool:
        max-idle: 6    #最大空闲数
        max-active: 10 #最大连接数
        min-idle: 2    #最小空闲数
    timeout: 2000      #连接超时
